language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.2.0"
  - "4.2.1"
  - "5.1.0"

branches:
  only:
    - master

before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev g++