language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.2.1"
  - "5.1"

matrix:
  allow_failures:
    - node_js: "5"

# Use `apt` from `node-canvas`
# https://github.com/Automattic/node-canvas/blob/v1.3.0/.travis.yml#L14-L25
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8
env:
  - CXX=g++-4.8